
mongo:
  image: mongo:3.2.12 
  volumes_from:
    - mongo-data
  ports:
    - "3184:27017"
  command: "--smallfiles --setParameter failIndexKeyTooLong=false"

mongo-data:
  image: mongo:3.2.12
  volumes:
    - ./.db/:/data/db
  command: "--break-mongo" # break mongod command and use it as data-volume-container
